### ISSUE TITLE
block 이름 충돌 문제

### ISSUE THREAD

**Issue by hhyein** [hhyein/OSS_project#13]
기존 rotation은 어떤 기능을 하는 역할인지 추측하기 어렵다고 판단되어
현재 block으로 이름을 변경하였습니다.
하지만 block 배열과 이름이 충돌하게 되는 다른 문제가 발생하였습니다.
이 문제를 어떻게 해결하는 것이 좋다고 생각하는지 comment 남겨주시기 바랍니다.

**Comment by hhyein** [comment]
저는 아래의 방법을 사용하여 문제를 해결하는 것이 좋을 것 같다고 생각하였습니다.
- block 배열 이름을 block_array으로 변경
- rotation -> block -> block_shape으로 변경

**Comment by Jisue** [comment]
block 배열 이름을 block_array로 바꾸는게 어떨까요?

**Comment by shuffle2479** [comment]
block배열 이름을 block_array로 바꾸는게 좋을것 같습니다

**Comment by hhyein** [comment]
넵 그러면 block 배열 이름을 block_array로 수정해서 프로젝트를 진행하시면 될 것 같습니다.

**Comment by shuffle2479** [comment]
네 block 배열 이름 block_array로 수정할게요
