### ISSUE TITLE
block 이름 충돌 문제

### ISSUE THREAD

**Issue by Jisue** [hhyein/OSS_project#7]
기존 rotation 변수명은 블록의 모양을 나타내는 의미를 표현하지 않다고 판단하였습니다.
따라서 기능에 맞게 변수명을 block으로 변경하려고 합니다.
하지만 기존 block 배열 이름과 충돌 문제가 발생했습니다.
기존 block 배열 이름을 block_array로 바꾸는게 어떨까요?

**Comment by hhyein** [comment]
넵 좋은 것 같습니다. 그러면 block 배열 이름을 block_array로 한 사람이 맡아서 바꾸는게 어떨까요?

**Comment by hhyein** [comment]
제가 block_array로 바꾸고 현재 pull request까지 작성하였습니다. 확인하시고 comment 작성 부탁드립니다!
